# Maximum width of each line
width = 80

# Time for each try
max_time = 60

# Max lines shown to type
lines_to_show = 2

# file 
file = "100_spanish"

# mode [ dictionary | file ]
mode = "dictionary"

# fps
fps = 120

# Line configuration
[config_line]

# Colors for each state of the line
selected = "#888888"
wrong = "#FF8888"
correct = "#44FF44"
