# Maximum width of each line
# width = 80

# Game time for the test
# max_time = 60

# Max lines shown
# lenght = 2

# File from which words are taken
# file = "100_spanish"

# Play mode. [ dictionary | file ]
# mode = "dictionary"

# update rate: 1000 suggested value
# rate = 1000

# Color theme (more coming soon)
# [theme] # Uncomment this line to change theme

# Selected char color
# selected = "#888888"

# Wrong char color
# wrong = "#FF8888"

# Right char color
# right = "#44FF44"
